### ISSUE TITLE
elenco relazioni menu a discesa non si aggiornano

### ISSUE THREAD

**Issue by pigreco** [pyarchinit/selectbyrelationship_repo#13]
@slarosa

prova da fare:

1. utilizzare progetto allegato;
2. aggiungere altra relazione;
3. nel menu Select relationship non compaiono le nuove relazioni,occorre necessariamente riavviare QGIS;
altra prova:

1. stesso progetto, APRILO e poi fai nuovo progetto (senza chiudere QGIS);
2. carica altri dati e fai una relazione;
3. le relazioni visibile dal plugin nel Select Relationship sono quelle del progetto precedente

[progetto e dati](https://github.com/pigreco/test_selectbyrelationshipv3/blob/master/dati_progetto_test.7z)

**Comment by pigreco** [comment]
@slarosa 

i punti 1,2,e,3 risolto, cioè compaiono le nuove relazioni.

Dal punto 4 in poi non funziona, ovvero noto questo:

creando un nuovo progetto (senza chiudere QGIS):
- carico due livelli e faccio una relazione (salvo progetto);
- appena attivo il plugin mi segnala questo errore:

```
2019-10-06T20:36:56     WARNING    Traceback (most recent call last):
              File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\selectbyrelationship_repo-master\select_by_relationship_plugin.py", line 231, in run
              self.updateSettings()
              File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\selectbyrelationship_repo-master\select_by_relationship_plugin.py", line 220, in updateSettings
              self.updateRelations()
              File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\selectbyrelationship_repo-master\select_by_relationship_plugin.py", line 263, in updateRelations
              self.sFr.setRelations(self.comboRelations.checkedItems())
              File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\selectbyrelationship_repo-master\select_by_relationship_handler.py", line 134, in setRelations
              self.relationsChecked = {rel: self.manager.relations()[rel] for rel in relations}
              File "C:/Users/pigre/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\selectbyrelationship_repo-master\select_by_relationship_handler.py", line 134, in 
              self.relationsChecked = {rel: self.manager.relations()[rel] for rel in relations}
             KeyError: 'rel_reg_prov'
```

nell'ultima riga noto `KeyError: 'rel_reg_prov'` che è il nome della relazione del progetto precedente.
